### ISSUE TITLE
Explanation about few-shot evaluation.

### ISSUE THREAD

**Issue by shlee625** [msxiaojin/MDLCC#3]
Hi. Thanks for your work. Actually I was waiting for the updates and I'm glad I can experiment this.
I'm trying to reproduce the few-shot evaluation part of your paper. I think there should be a meta-model trained with 7 subsets of NUS dataset to finetune on the few-shot dataset. But it seems that the names of folders in ``models`` indicate the training sets and there is no meta-model weight in ``models``. Do I have to train my own meta-model with 7 subsets of NUS like in the paper?
It would be grateful if you can provide some information to reproduce the results of few-shot evaluations (Section 4.5 in the paper) in detail.
Thank you.

**Comment by msxiaojin** [comment]
> Hi. Thanks for your work. Actually I was waiting for the updates and I'm glad I can experiment this.
> I'm trying to reproduce the few-shot evaluation part of your paper. I think there should be a meta-model trained with 7 subsets of NUS dataset to finetune on the few-shot dataset. But it seems that the names of folders in `models` indicate the training sets and there is no meta-model weight in `models`. Do I have to train my own meta-model with 7 subsets of NUS like in the paper?
> It would be grateful if you can provide some information to reproduce the results of few-shot evaluations (Section 4.5 in the paper) in detail.
> Thank you.

Hi, I just realized I forgot to upload the trained meta-models, and didn't add comments on 'FewShot.py'. Please find the meta-models in './fewshot' folder, and the revised 'FewShot.py'. The meta-models were trained using 'awb_demo.py' by specifying camera_names, which is, the 7 subsets of NUS. The few-shot evaluation is done by run 'FewShot.py' on 3-fold cross validation.

**Comment by shlee625** [comment]
Thanks for your help. Take care.
